---

# TODO: Use this when it will work
#- name: 'Set broker clusterresourcedefinitions state={{ state }}'
#  k8s_raw:
#    state: '{{ state }}'
#    definition: "{{ lookup('template', item) | from_yaml }}"
#  with_items:
#    - bundle.crd.yaml
#    - jobstates.crd.yaml
#    - servicebindings.crd.yaml
#    - serviceinstances.crd.yaml
#
#
- name: 'Use kubectl to {{ kubectl_action }} cluster resource definitions'
  command: kubectl {{ kubectl_action }} -f {{ lookup('fileglob', item) }}
  register: crd_command
  failed_when: crd_command.rc != 0 and 'AlreadyExists' not in crd_command.stderr and 'NotFound' not in crd_command.stderr
  with_items:
    - bundle.crd.yaml
    - jobstates.crd.yaml
    - servicebindings.crd.yaml
    - serviceinstances.crd.yaml
  when: broker_image_tag != "canary"

- name: 'Use kubectl to {{ kubectl_action }} cluster resource definitions'
  command: kubectl {{ kubectl_action }} -f {{ lookup('fileglob', item) }}
  register: crd_command
  failed_when: crd_command.rc != 0 and 'AlreadyExists' not in crd_command.stderr and 'NotFound' not in crd_command.stderr
  with_items:
    - bundle.crd-canary.yaml
    - bundlebindings.crd-canary.yaml
    - bundleinstances.crd-canary.yaml
  when: broker_image_tag == "canary"

