---

- name: 'Set broker clusterresourcedefinitions state={{ state }}'
  k8s:
    state: '{{ state }}'
    definition: "{{ lookup('file', item) | from_yaml }}"
  loop:
    - bundle.crd.yaml
    - jobstates.crd.yaml
    - servicebindings.crd.yaml
    - serviceinstances.crd.yaml
