---

# This file is only for kubernetes specific actions related to deployment.
# The main driver for separate files is the fact that, in kubernetes, a
# TLS secret must be created for the broker. Logic shouldn't be added here
# unless absolutely necessary.

# TODO: Figure out how to use openssl from ansible
#- name: Generate a Self Signed OpenSSL certificate
#  openssl_certificate:
#    path: /tmp/{{ broker_name }}-cert/cert.pem
#    privatekey_path: /tmp/{{ broker_name }}-cert/key.pem
#    subject: "/CN={{ broker_name }}.{{ broker_name }}.svc"
#    provider: selfsigned
- name: 'Create directory for OpenSSL cert'
  file:
    path: /tmp/{{ broker_name }}-cert
    state: directory
  when: cluster == 'kubernetes' and apb_action == 'provision'

- name: 'Generate OpenSSL cert for broker'
  command: >
    openssl req -nodes -x509 -newkey rsa:4096
    -keyout /tmp/{{ broker_name }}-cert/key.pem
    -out /tmp/{{ broker_name }}-cert/cert.pem
    -days 365
    -subj "/CN={{ broker_name }}.{{ broker_name }}.svc"
  when: cluster == 'kubernetes' and apb_action == 'provision'

- name: 'Create broker-tls secret'
  command: >
    kubectl create secret tls -n {{ broker_namespace }} {{ broker_name }}-tls
    --cert="/tmp/{{ broker_name }}-cert/cert.pem"
    --key="/tmp/{{ broker_name }}-cert/key.pem"
  register: tls_command
  failed_when: tls_command.rc != 0 and 'AlreadyExists' not in tls_command.stderr
  when: cluster == 'kubernetes' and apb_action == 'provision'

- name: Set facts for service catalog
  set_fact:
    broker_ca_crt: "{{ lookup('file', '/tmp/' + broker_name + '-cert/cert.pem') | b64encode }}"
    broker_client_secret: "{{
      lookup(
        'k8s',
        kind='ServiceAccount',
        namespace=broker_namespace,
        resource_name=broker_name + '-client'
        ) | json_query('secrets') | first | json_query('name')
    }}"
  when: apb_action == 'provision'

- name: 'Set broker deployment object state={{ state }}'
  openshift_raw:
    state: '{{ state }}'
    definition: "{{ lookup('template', 'broker.deployment.yaml') | from_yaml }}"
