---

apiVersion: v1
kind: Secret
metadata:
  name: {{ broker_name }}-auth-secret
  namespace: {{ broker_namespace }}
data:
  username: {{ broker_basic_auth_username | b64encode }}
  password: {{ broker_basic_auth_password | b64encode }}
