---

apiVersion: v1
kind: Secret
metadata:
  name: {{ broker_name }}-client
  namespace: {{ broker_namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ broker_name }}-client
type: kubernetes.io/service-account-token
