---

apiVersion: v1
{% if cluster == 'kubernetes' %}
kind: Deployment
{% else %}
kind: DeploymentConfig
{% endif %}
metadata:
  name: {{ broker_name }}
  namespace: {{ broker_namespace }}
  labels:
    app: {{ broker_name }}
    service: {{ broker_name }}
spec:
  replicas: 1
{% if cluster == 'kubernetes' %}
  selector:
    matchLabels:
      app: {{ broker_name }}
      service: {{ broker_name }}
  strategy:
    type: RollingUpdate
{% else %}
  selector:
    app: {{ broker_name }}
    service: {{ broker_name }}
  strategy:
    type: Rolling
{% endif %}
  template:
    metadata:
      labels:
        app: {{ broker_name }}
        service: {{ broker_name }}
    spec:
      serviceAccount: {{ broker_name }}
      containers:
      - image: {{ broker_image }}
        name: broker
        imagePullPolicy: {{ broker_image_pull_policy }}
        volumeMounts:
          - name: config-volume
            mountPath: /etc/{{ broker_name }}
          - name: {{ broker_name }}-tls
            mountPath: /etc/tls/private
{% if broker_basic_auth_enabled | bool %}
          - name: {{ broker_name }}-auth-volume
            mountPath: /var/run/asb-auth
{% endif %}
        ports:
          - containerPort: 1338
            protocol: TCP
        env:
        - name: BROKER_CONFIG
          value: /etc/{{ broker_name }}/config.yaml
        resources: {}
        terminationMessagePath: /tmp/termination-log
        readinessProbe:
          httpGet:
            path: /healthz
            port: 1338
            scheme: HTTPS
          initialDelaySeconds: {{ broker_probe_initial_delay }}
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            port: 1338
            path: /healthz
            scheme: HTTPS
          initialDelaySeconds: {{ broker_probe_initial_delay }}
          timeoutSeconds: 1
      volumes:
        - name: config-volume
          configMap:
            name: broker-config
            items:
            - key: broker-config
              path: config.yaml
        - name: {{ broker_name }}-tls
          secret:
            secretName: {{ broker_name }}-tls
{% if broker_basic_auth_enabled | bool %}
        - name: {{ broker_name }}-auth-volume
          secret:
            secretName: {{ broker_name }}-auth-secret
{% endif %}
