---

apiVersion: v1
kind: Service
metadata:
  name: {{ broker_name }}
  namespace: {{ broker_namespace }}
  labels:
    app: {{ broker_name }}
    service: {{ broker_name }}
{% if cluster == 'openshift' %}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ broker_tls_name }}
{% endif %}
spec:
  ports:
    - name: port-1338
      port: 1338
      targetPort: 1338
      protocol: TCP
  selector:
    app: {{ broker_name }}
    service: {{ broker_name }}
