---

apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
  namespace: {{ broker_namespace }}
  labels:
    app: {{ broker_name }}
data:
  broker-config: |
    registry:
{% if broker_dockerhub_enabled | bool %}
      - type: dockerhub
        name: {{ broker_dockerhub_name }}
        url: {{ broker_dockerhub_url }}
        org: {{ broker_dockerhub_org | quote }}
        tag: {{ broker_dockerhub_tag | quote }}
        white_list:
{%     for item in broker_dockerhub_white_list %}
          - {{ item | quote }}
{%     endfor %}
{% endif  %}
{% if broker_local_openshift_enabled | bool %}
      - type: local_openshift
        name: {{ broker_local_openshift_name }}
        namespaces:
{%     for item in broker_local_openshift_namespaces %}
          - {{ item | quote }}
{%     endfor %}
        white_list:
{%     for item in broker_local_openshift_white_list %}
          - {{ item | quote }}
{%     endfor %}
{% endif  %}
{% if broker_helm_enabled | bool %}
      - type: helm
        name: {{ broker_helm_name }}
        url: {{ broker_helm_url }}
        runner: {{ broker_helm_runner }}
        white_list:
{%     for item in broker_helm_white_list %}
          - {{ item | quote }}
{%     endfor %}
{% endif %}
    dao:
      type: {{ broker_dao_type | quote }}
{% if broker_dao_type == 'etcd' %}
      etcd_host: {{ etcd_host }}
      etcd_port: {{ etcd_port }}
{%   if cluster == 'kubernetes' %}
      etcd_ca_file: /var/run/etcd-ca/ca.crt
{%   else %}
      etcd_ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
{%   endif %}
      etcd_client_cert: /var/run/etcd-auth/client.crt
      etcd_client_key: /var/run/etcd-auth/client.key
{% endif %}
    log:
      logfile: /var/log/ansible-service-broker/asb.log
      stdout: true
      level: debug
      color: true
    openshift:
      host: ''
      ca_file: ''
      bearer_token_file: ''
      image_pull_policy: {{ broker_image_pull_policy | quote }}
      sandbox_role: {{ broker_sandbox_role | quote }}
      namespace: {{ broker_namespace | quote }}
      keep_namespace: {{ broker_keep_namespace }}
      keep_namespace_on_error: {{ broker_keep_namespace_on_error }}
    broker:
      dev_broker: {{ broker_dev }}
      bootstrap_on_startup: {{ broker_bootstrap_on_startup }}
      refresh_interval: {{ broker_refresh_interval | quote }}
      launch_apb_on_bind: {{ broker_launch_apb_on_bind }}
      output_request: {{ broker_output_request }}
      recovery: {{ broker_recovery }}
      ssl_cert_key: /etc/tls/private/tls.key
      ssl_cert: /etc/tls/private/tls.crt
      auto_escalate: {{ broker_auto_escalate }}
      cluster_url: {{ broker_namespace }}
{% if cluster == 'openshift' %}
      dashboard_redirector: http://{{
        lookup(
          'k8s',
          api_version='route.openshift.io/v1',
          kind='Route',
          namespace=broker_namespace,
          resource_name='broker-redirector'
        ) | json_query('spec.host')
      }}
{% endif %}
      auth:
        - type: basic
          enabled: {{ broker_basic_auth_enabled }}
