---

apiVersion: v1
kind: Service
metadata:
  name: {{ etcd_name }}
  namespace: {{ broker_namespace }}
  labels:
    app: {{ etcd_name }}
    service: {{ etcd_name }}
{% if cluster == 'openshift' %}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ etcd_tls_name }}
{% endif %}
spec:
  ports:
    - name: etcd-port
      port: {{ etcd_port }}
      targetPort: {{ etcd_port }}
      protocol: TCP
  selector:
    app: {{ etcd_name }}
    service: {{ etcd_name }}
