---

- name: automation-broker-apb test playbook
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    # Test etcd
    - name: Provision test with ETCD
      include_role:
        name: automation-broker-apb
      vars:
        apb_action: provision
        create_broker_namespace: true

    - name: Wait for clusterservicebroker to become available
      command: kubectl get clusterservicebrokers automation-broker -o go-template={%raw%}'{{ range .status.conditions }}{{ if eq .type "Ready" }}{{ .status }}{{ end }}{{ end }}'{%endraw%}
      register: broker_ready
      retries: 60
      delay: 10
      until: broker_ready.stdout == 'True'

    - name: Deprovision test with ETCD
      include_role:
        name: automation-broker-apb
      vars:
        apb_action: deprovision
        create_broker_namespace: true

    - name: Wait for namespace to be destroyed
      vars:
        namespace_lookup: "{{ lookup('k8s', kind='Namespace', resource_name='automation-broker') }}"
      set_fact:
        _namespace_status: "{{ namespace_lookup }}"
      retries: 10
      delay: 5
      until:
        - not namespace_lookup
