---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: automationbrokers.apps.fabianism.us
spec:
  group: apps.fabianism.us
  names:
    kind: AutomationBroker
    listKind: AutomationBrokerList
    plural: automationbrokers
    singular: automationbroker
  scope: Namespaced
  version: v1alpha1
